import { createContext, useContext, useState } from "react";

// Bilingual project data
export const projectsData = {
  fr: {
    "comptoir": {
      title: "Comptoir & Bordereau",
      subtitle: "Deux outils pour agences de voyages à modèle de langage encadré — Projet personnel",
      type: "Logiciel / IA appliquée",
      role: "Développeur solo",
      description: "Un client de voyages formule sa demande comme il la dirait au téléphone ; Comptoir rend les séjours qui correspondent vraiment, avec leur prix réel pour cette composition familiale — et quand rien ne correspond, il nomme le critère à assouplir plutôt que de proposer quelque chose d'approchant. Le modèle de langage comprend la demande et rédige la réponse ; il ne décide de rien. Tout ce qui est vérifiable est tranché en Python. Bordereau applique la même règle aux courriers d'hôteliers : il en tire une ligne par réservation, et le modèle n'y produit aucune valeur — il désigne seulement, parmi les candidats déjà relevés dans le courrier, celle qui va avec la réservation.",
      highlights: [
        "Séparation stricte entre ce que fait le modèle (comprendre la phrase, rédiger la réponse) et ce que fait le code : prix, dates, capacité des chambres, formule de restauration, aéroport de départ sont tranchés en Python, avec des comparaisons — aucun modèle n'est appelé pour savoir si 3 293 € tient dans un budget de 3 000 €",
        "Chaque phrase de la réponse est rattachée par le modèle à un champ d'une fiche précise, puis re-vérifiée contre cette fiche avant affichage : une fiche jamais présentée au modèle, un champ inexistant ou un prix qui ne correspond pas au montant réellement calculé sont retirés et journalisés, jamais montrés au client",
        "Quand rien ne correspond, le modèle n'est pas appelé du tout — c'est le moteur qui nomme le critère à assouplir, dans l'ordre où un agent négocie réellement : le budget d'abord, les dates ensuite, la destination en dernier",
        "Le même filtrage reporté en SQLite (requête paramétrée avec EXISTS sur des tables normalisées) et confronté fiche par fiche et prix par prix à l'implémentation Python sur les 20 mêmes requêtes — le portage n'est pas supposé correct parce qu'il ressemble à l'original, il est vérifié contre lui",
        "167 tests, dont les contrôles de contraintes dures ré-implémentés à la main plutôt qu'en appelant les fonctions du moteur : un test qui vérifie le code avec le code testé se contente de confirmer que la fonction est d'accord avec elle-même",
        "Mesure en conditions réelles avec le modèle dans la boucle sur 20 demandes : extraction 20/20, abstention correcte 8/8 sur les cas insolubles, traçabilité moyenne 0,86 — et les motifs de rejet enregistrés, ce qui permet de distinguer un modèle qui invente d'un modèle qui bafouille",
        "Reprise de contexte : « même chose mais pas plus de 3 000 euros » ne repart pas de zéro. Le modèle ne voit toujours que la dernière phrase ; c'est le code qui reprend champ par champ ce qu'elle ne mentionne pas. L'abstention est passée de 6/8 à 8/8 après ce correctif",
        "Le noyau ne dépend que de la bibliothèque standard Python. L'interface web (FastAPI) vit dans un fichier de dépendances séparé pour ne pas casser cette règle, et une façade Spring Boot (JDK 17) expose le service en HTTP avec validation des requêtes",
        "Trois défauts trouvés uniquement en mesurant ou en utilisant, pas en relisant : réponses tronquées par la fenêtre de contexte, boucles de répétition du modèle sur les listes, et une reprise de critères automatique qui faisait cumuler deux demandes sans rapport dès le deuxième essai",
        "Bordereau — lecture de courriers d'hôteliers et de réceptifs (une dizaine de champs par réservation : hôtel, dates, chambres, prix, interlocuteur). L'erreur visée n'est pas l'invention mais le mauvais rattachement : un prix réel collé au mauvais hôtel, que la vérification « est-ce que la valeur apparaît dans le courrier ? » laisse passer",
        "Bordereau — listes fermées (un hôtel doit venir du référentiel), provenance gardée pour chaque valeur, et un modèle qui ne répond qu'un numéro de candidat ou null : il ne peut ni inventer ni combler un trou réel. Mesuré avec gemma4:12b en local sur 20 courriers piégés : 98,5 % des champs trouvés, 100 % bien rattachés (263/263), 33 champs sans réponse tous laissés vides, 9 incertitudes sur 9 signalées",
        "Bordereau — la mesure a été vérifiée avant l'extracteur, sur de faux extracteurs au défaut connu : celui qui échange les hôtels obtient 100 % de champs trouvés et seulement 75 % sur hotel_id, d'où le détail champ par champ. Interface web qui colore dans le courrier l'endroit exact où chaque valeur a été lue, corrections qui enrichissent le jeu de mesure sans que l'outil n'apprenne dans le dos des utilisateurs, 50 tests sans réseau",
      ],
      sections: [
        { title: "Le modèle comprend, le code décide", text: "Dans le tourisme, une hallucination n'est pas une curiosité : c'est un client qui arrive dans un hôtel sans le club enfants qu'on lui a promis. Le modèle de langage est donc cantonné à deux tâches — traduire une phrase libre en demande structurée, et rédiger la réponse finale. Tout ce qui se vérifie est tranché en Python, par des comparaisons. La sortie du modèle elle-même n'est pas crue sur parole : un JSON peut arriver entouré de balises markdown, tronqué, ou porter une formule qui n'existe pas dans le catalogue — ce qui est invalide est écarté, jamais deviné, et signalé comme non précisé." },
        { title: "Vérifié affirmation par affirmation", text: "La rédaction ne se fait pas en texte libre : le modèle ne voit que les fiches déjà retenues par le filtrage, et doit rendre un JSON où chaque phrase cite explicitement un champ d'une fiche précise. Un vérificateur re-cherche ensuite chaque affirmation dans la fiche citée et retire tout ce qui ne correspond pas. Sur un passage de mesure, 12 affirmations sur 63 ont été écartées — aucune pour avoir contredit une fiche, toutes pour avoir été annoncées puis laissées vides." },
        { title: "Le même moteur, deux fois", text: "Les critères qui se ramènent à une appartenance à un ensemble ont été réécrits en SQLite, dans une seule requête paramétrée. La période et le prix restent en Python — une intersection de plages de dates et une remise enfant n'ont pas leur place dans une clause WHERE sans devenir illisibles. Un test recompose le résultat complet et vérifie qu'il est identique, fiche par fiche et prix par prix, à celui du moteur Python sur les mêmes requêtes." },
        { title: "Bordereau : vérifier le lien, pas la présence", text: "Sur un courrier qui porte trois hôtels, quatre prix et deux dates d'arrivée, un modèle n'invente rien : il croise deux réservations. Bordereau découpe donc le courrier en blocs autour des références de dossier et ne cherche une valeur que dans son bloc — sans modèle, 96 % des champs sont trouvés et aucun n'est mal rattaché. Le modèle n'intervient que sur les champs restés vides, un à la fois, et ne peut répondre qu'un numéro parmi les candidats présentés. Sa seule erreur possible est donc exactement celle que la mesure détaille champ par champ." },
      ],
    },
    "claude-ue5": {
      title: "Pilotage & vérification d'un moteur 3D",
      subtitle: "C++, Python, CI — plugin Unreal Engine 5 piloté par IA, 117 tests — Projet personnel",
      type: "Outil / IA",
      role: "Développeur solo",
      description: "Plugin C++ et pont MCP qui permettent de construire des scènes 3D dans Unreal Engine 5 par script, piloté par une IA conversationnelle. Rien n'est sauvegardé sans vérification : 117 tests automatiques rejoués à chaque modification (dont 6 en intégration continue), contrôles de collision, capture d'écran et playtest automatisé.",
      highlights: [
        "Pont MCP (Remote Execution API) qui permet à un agent externe (Claude Code / Claude Cowork) de piloter l'éditeur UE5 en langage naturel — génération de niveaux, création de mécaniques de gameplay, vérification automatique du travail produit",
        "Panneau Slate C++ dockable (Tools → Claude AI) intégré nativement dans l'éditeur, pour un usage local sans dépendre d'un outil externe",
        "Suite de 117 tests automatiques (111 dans l'éditeur + 6 en CI GitHub Actions) qui valide chaque modification du plugin avant qu'elle soit acceptée — aucune régression silencieuse",
        "Agent de playtest autonome : découvre seul son parcours sur n'importe quel niveau (objectifs interactifs, ennemis, couverture du NavMesh, sans coordonnées en dur), pilote le personnage en jeu (PIE) et journalise les événements (détection ennemie, blocages, jumpscares) — a détecté et permis de corriger un vrai bug empêchant les ennemis de poursuivre le joueur",
        "trust_gate : l'intégrité d'un fichier est vérifiée plutôt que supposée — plusieurs canaux d'accès indépendants enregistrent chacun une empreinte SHA-256 du même fichier, et un verdict TRUSTED / DIVERGENT n'est rendu qu'en les comparant. A attrapé en conditions réelles des fichiers périmés ou tronqués sans aucune erreur levée",
        "BatchWireGraph : DSL JSON qui câble un graphe Blueprint entier (nœuds + connexions) en un seul appel, au lieu de 20+ appels d'API unitaires",
        "Placement zéro-overlap (safe_spawn_enemy) : grille d'occupation + raycast de sol + vérification physique réelle — un acteur qui atterrirait dans un mur est repositionné automatiquement, jamais validé tel quel",
        "Vérification visuelle non-régressive (SSIM approximé par blocs) : chaque zone validée devient une image de référence, toute reconstruction future est comparée pour détecter une dérive silencieuse (lumière déplacée, matériau changé)",
        "100% open-source, CI GitHub Actions à chaque commit — 25 comportements non documentés de l'API UE5.7 identifiés et contournés (voir docs/KNOWN_ISSUES.md)",
      ],
      sections: [
        { title: "Deux façons de piloter l'éditeur", text: "Un pont MCP (Remote Execution API) permet à un agent externe comme Claude Code ou Claude Cowork de piloter l'éditeur UE5 depuis une simple conversation. En complément, un panneau Slate C++ dockable (Tools → Claude AI) offre le même type d'exécution Python directement dans l'éditeur, sans dépendance externe." },
        { title: "Vérification avant chaque sauvegarde", text: "Aucun résultat n'est accepté à l'aveugle : verify_level.py scanne automatiquement les acteurs en collision, les lumières mal configurées, le NavMesh non reconstruit ; une capture d'écran synchrone (contournement d'un bug de rendu UE5) permet une relecture visuelle systématique avant tout save()." },
        { title: "Agent de playtest autonome", text: "Un module dédié pilote le personnage joueur en PIE via des waypoints et un pathfinding NavMesh réel, journalise les événements de gameplay (détection, poursuite, jumpscare) et permet de rejouer un scénario de façon reproductible — c'est cet agent qui a mis en évidence un vrai bug de comportement ennemi, invisible en test statique." },
        { title: "BlueprintEditingSubsystem & suite anti-régression", text: "BlueprintEditingSubsystem expose une API C++ pour câbler des graphes Blueprint entiers en un seul appel (BatchWireGraph DSL). Avant et après toute modification du plugin, une suite de 117 tests revalide chaque subsystem — une régression est bloquée avant d'atteindre le niveau." },
      ],
    },
    "level-design-tools": {
      title: "Banc de test automatisé — outil 3D",
      subtitle: "C#, Unity 6 — 40 000 cas vérifiés, 21 défauts injectés, 4 vrais bugs trouvés — Projet personnel",
      type: "Tests / Vérification",
      role: "Développeur solo",
      description: "Un outil d'éditeur 3D (Unity) et surtout le banc de test qui le vérifie : 40 000 cas exercés en quelques secondes, là où chaque cas demandait un essai manuel dans l'éditeur. La fiabilité du banc elle-même est mesurée en y injectant 21 défauts volontaires — 19 détectés — et il a trouvé 4 vrais bugs dans du code qui compilait et semblait fonctionner.",
      highlights: [
        "Room Builder : trois modes d'éditeur — salle paramétrique, contour dessiné dans la vue Scene puis extrudé avec la hauteur au curseur (aimantation Ctrl, sens donné par le geste), et découpe d'ouvertures directement sur la surface survolée",
        "La découpe ne retire pas de matière : le panneau conserve sa description logique (contour, épaisseur, liste des trous) sur un composant sérialisé et son maillage est régénéré entièrement à chaque fois — un mur reste découpable indéfiniment, chaque ouverture est annulable",
        "Géométrie sans aucune dépendance à l'API Unity : elle se compile et s'exerce hors de l'éditeur, ce qui permet d'exercer 40 000 panneaux en quelques secondes au lieu d'un aller-retour dans Unity à chaque essai",
        "14 propriétés vérifiées plutôt que des résultats figés — conservation d'aire, couverture exacte (un point dans la matière couvert par exactement un triangle, un point dans un trou par aucun), étanchéité du prisme, volume égal à aire × épaisseur, indépendance à l'échelle, déterminisme",
        "Mutation testing maison : 21 défauts plausibles injectés un par un dans le code de géométrie, recompilés, confrontés à la batterie — 19 rattrapés. La mesure est partie de 67 %, chaque palier a été gagné en écrivant la propriété qui manquait",
        "Quatre bugs réels trouvés dans du code qui compilait et fonctionnait à l'écran : seuil absolu rendant le maillage dépendant de la position du mur dans le niveau, extrapolation posant un sommet à l'intérieur d'un trou voisin (1 cas sur 1500), fissure de 15 µm entre une face et son chant, cylindre accepté comme boîte",
        "Vérification en couches — compilateur, propriétés hors moteur, sonde dans l'éditeur en direct via MCP, œil humain : chacune attrape une classe de défaut que les autres ne peuvent structurellement pas voir. Le cylindre n'a pu être trouvé qu'en interrogeant Unity en direct",
        "Le mutation testing a aussi révélé 137 lignes de code mort : un défaut injecté qui survit sans explication frappe souvent du code dont plus rien ne dépend",
        "Trois fausses alertes du banc lui-même, diagnostiquées et corrigées côté test : calibrer les propriétés sur le contrat réel du code (un sommet à 1,6 µm d'une arête de 2,7 m n'est pas dessus) représente une bonne part du travail — un harnais qui crie au loup est abandonné en trois jours",
      ],
      sections: [
        { title: "Trois modes de blockout", text: "Le mode Boîte produit une salle rectangulaire à partir de dimensions. Le mode Dessin libre laisse cliquer un contour dans la vue Scene : une fois fermé, la hauteur suit la souris jusqu'au clic de validation, Ctrl aimante sur la grille et tirer sous le plan de dessin extrude vers le bas. Le mode Découpe perce une ouverture — porte, fenêtre, trémie — directement sur la surface survolée. La découpe accepte tout contour plat extrudé, y compris une boîte venue d'ailleurs ; un cylindre ou une sphère sont refusés avec la raison, parce que la reconstruction les remplacerait par une boîte." },
        { title: "Des propriétés, pas des résultats figés", text: "La triangulation et l'assemblage 3D ne dépendent d'aucune API Unity — une centaine de lignes de doublures pour Vector2, Vector3 et Mathf suffisent. Le banc compile donc les fichiers du projet, pas des copies, et les exerce hors éditeur. Ce qui est vérifié n'est pas une liste de résultats attendus mais des propriétés qui doivent tenir pour n'importe quelle entrée. Les cas tirés au hasard sont complétés par des régressions figées — chacune est un défaut qui a réellement existé, et chacune a été vue échouer sur la version qui le portait." },
        { title: "Mesurer ce que la vérification vaut", text: "Une batterie de tests qui passe ne dit pas ce qu'elle attraperait. Le harnais de mutation injecte 21 défauts plausibles, un par un, et compte combien la batterie en rattrape : 19 sur 21. Les deux survivants frappent du code dont rien ne dépend. La mesure est partie de 67 % — les propriétés ajoutées depuis existent parce qu'un défaut injecté passait sans être vu, pas parce qu'elles semblaient une bonne idée." },
      ],
    },
    "horror-ue5": {
      title: "Projet Horreur", subtitle: "Jeu d'horreur à la première personne — Projet personnel", type: "Horreur", role: "Développeur solo",
      description: "Jeu d'horreur solo à la première personne sur Unreal Engine 5.7. Le joueur traverse des salles hantées par des mannequins qui avancent dès qu'on ne les éclaire plus : la lampe torche est à la fois la seule défense et la seule façon de voir. Pour gagner, il faut atteindre la dernière zone et actionner l'interrupteur. Les niveaux ont été construits et vérifiés avec ma toolchain Agent IA × UE5.",
      highlights: [
        "IA des mannequins en Behavior Tree (éclairé → étourdi → poursuite → patrouille) avec AI Perception : un ennemi pris dans le faisceau de la lampe torche s'arrête, dès qu'il sort de la lumière il reprend la chasse",
        "Boucle de jeu complète : lampe torche à ramasser, jumpscares déclenchés à l'approche, interrupteur final qui fait disparaître les ennemis et lance la séquence de victoire, menu principal en surimpression sur le niveau en pause",
        "Plusieurs niveaux jouables, dont HorrorLevel (9 zones et couloirs) et SanatoriumLevel, un niveau d'ambiance « isolement et folie » construit de bout en bout puis parcouru jusqu'à la victoire par l'agent de playtest",
        "Ambiance réglée pour l'horreur : GI Lumen coupée au profit d'ombres dures, exposition manuelle, vignette, grain et désaturation, composition en quatre sources de lumière par salle, néons qui clignotent",
        "Vignette rouge pilotée en C++ (VignetteManager) quand un ennemi voit le joueur sans être éclairé",
        "Bug réel trouvé par l'agent de playtest : la perception de tous les ennemis était désactivée sur le template du composant, plus aucune poursuite possible — invisible à tout contrôle statique, corrigé et revérifié en jeu",
      ],
      sections: [],
    },
    "hover-ue5": {
      title: "HoverCharacter UE5", subtitle: "Personnage hover procédural — Projet personnel", type: "Gameplay / Physique", role: "Développeur solo",
      description: "Système de personnage C++ en UE5.8 combinant marche standard et mode hover, avec banking, alignement de surface et accélération sur pente. Terrain désertique procédural généré en C++, et calibrage physique itératif par comparaison avec des jeux hover de référence pour obtenir un ressenti crédible.",
      highlights: [
        "HoverCharacter C++ — dual mode marche/hover avec banking dynamique, alignement de surface par trace et accélération sur pente calculée depuis la normale du sol",
        "Terrain procédural désert (ADesertTerrain) via ProceduralMeshComponent — 5 octaves de bruit de Perlin, LOD dynamique",
        "Calibrage physique itératif par comparaison avec des références de vol externes (jeux à mécanique hover similaire), pour obtenir une sensation crédible plutôt que des valeurs choisies au hasard",
        "Contournement documenté d'un bug UE5.7/5.8 (modifiers Enhanced Input non persistants entre sessions) via IsInputKeyDown() avec mapping AZERTY explicite — la même solution retrouvée et réappliquée sur un second projet (voir RPG 3e personne)",
      ],
      sections: [
        { title: "HoverCharacter — Dual Mode C++", text: "Le personnage bascule entre marche standard et mode hover (lévitation, banking latéral, alignement de surface par trace). L'accélération sur pente est calculée à partir du vecteur normal du sol — plus la pente est raide, plus le boost est fort." },
        { title: "Terrain procédural & calibrage physique", text: "ADesertTerrain génère un terrain désertique en C++ via ProceduralMeshComponent avec 5 octaves de bruit de Perlin. La physique du mode hover a été calibrée de façon itérative, par comparaison avec des jeux de référence proposant une mécanique de vol similaire, pour obtenir un ressenti cohérent avec les attentes du joueur." },
        { title: "Contournement bug Enhanced Input UE5.8", text: "Bug documenté : les modifiers Enhanced Input ne persistent pas entre sessions PIE en UE5.7/5.8. Solution : remplacement par IsInputKeyDown() sur les axes critiques, avec mapping AZERTY explicite. Solution reproductible, documentée, et déjà réutilisée sur un projet suivant." },
      ],
    },
    "assistant-ue5-local": {
      title: "Assistant IA local × UE5",
      subtitle: "Assistant qui pilote Unreal Engine 5.8 en langage naturel, 100 % en local, et la boîte à outils du projet GameAnimationSample — Projet personnel",
      type: "Outil / IA locale",
      role: "Développeur solo",
      description: "Un assistant en langage naturel qui pilote Unreal Engine 5.8 en tournant entièrement sur ma carte graphique : pas de compte, pas d'abonnement, pas de connexion une fois installé. Son terrain est GameAnimationSample, autour duquel se sont construits quatre plugins Unreal Engine 5.8 et un harnais d'évaluation, réunis sous une contrainte tenue du début à la fin : rien ne se pilote à l'écran. Tout — construire un niveau, câbler un Behavior Tree, jouer une session pour vérifier un comportement — doit passer par du script. C'est cette contrainte qui a forcé à écrire les outils qui manquaient, puis à vérifier qu'ils font ce qu'ils prétendent, et enfin à vérifier que l'agent qui les utilise respecte lui-même les règles du projet.",
      highlights: [
        "Assistant UE5 local — Qwen2.5-Coder 14B via Ollama sur une RTX 4070, boucle d'agent et client MCP maison branchés sur les serveurs Unreal (dont celui du projet : PNJ, Behavior Trees, playtest). Aucune connexion Internet une fois installé",
        "RAG construit depuis l'éditeur lui-même : 14 572 méthodes de l'API Python d'UE 5.8.2 et 3 931 assets du projet avec leurs vrais chemins, pour que le modèle cesse d'inventer des fonctions et des chemins qui n'existent pas. Conventions du projet injectées à chaque message, règles situationnelles servies seulement quand elles concernent la question",
        "Garde-fous côté code plutôt que confiance dans le modèle : confirmation avant tout outil qui modifie le projet (une phrase en réponse redirige le modèle), appel d'outil écrit en texte exécuté seulement si l'outil existe vraiment, plafond de temps sur chaque appel MCP, journal des pannes, et impossibilité d'annoncer une réussite après un échec d'outil — 22 scripts de test avec un faux modèle, sans Unreal",
        "BlockoutTools — outil de level design Slate pour UE5.8 : salle paramétrique, contour dessiné dans le viewport puis extrudé en direct (Ctrl contraint à angles droits, Ctrl+F ferme d'équerre), et découpe de portes et fenêtres sur la surface survolée. Le panneau est livré à quelqu'un qui ne programme pas, avec une notice d'installation en trois minutes et une ligne de statut qui explique toujours ce qui s'est passé",
        "La géométrie de BlockoutTools ne dépend d'aucune API Unreal — une centaine de lignes de doublures suffisent à la compiler hors moteur. Le harnais exerce donc les fichiers du projet, pas des copies : 40 000 contours en une seconde, contre un rebuild du plugin (éditeur fermé, ~2 min) plus un aller-retour dans l'éditeur",
        "Des propriétés plutôt que des résultats figés : aire triangulée égale à l'aire du contour moins les trous, couverture exacte, prisme recto-verso d'épaisseur juste, seuil de dégénérescence relatif à la taille du panneau, aucune T-jonction, déterminisme au bit près",
        "Un bug du harnais lui-même, trouvé avant qu'il ne serve : le générateur de contours tirait des angles uniformes puis les triait, ce qui ne donne un polygone simple que si les sommets font le tour du centre — 57 contours auto-intersectants sur 2 000 étaient reprochés au code testé. Deux seuils ont aussi dû être recalés sur le contrat réel du code plutôt que sur une intuition",
        "BTAuthoringKit — plugin C++ qui expose une API scriptable pour construire des Behavior Trees complets (Blackboard, composites, tasks, decorators, services, graphe visuel inclus) sans jamais ouvrir l'éditeur de graphe. Écrit parce que ni l'API Python d'Unreal ni l'outillage Blueprint existant ne savent éditer le graphe d'un Behavior Tree",
        "Injection d'input au même point qu'une vraie pression de touche : elle traverse l'Input Mapping Context, les modifiers et les triggers. Mesuré en PIE réelle, 1037 cm parcourus en 4 s. C'est ce qui rend la vérification comportementale possible sans jamais piloter l'écran — les deux voies naturelles étant mortes, chacune pour une raison distincte",
        "Un test de non-régression qui pilote seul une session de jeu (~52 s de temps de jeu) et vérifie sept points par le comportement réel plutôt que par l'état des données : arbre lancé, controller unique, déplacement, animation d'assise, détection par perception réelle, rapprochement du joueur, aucun PNJ figé",
        "IA de PNJ à tolérance et habituation : trois niveaux d'attention écrits dans le Blackboard à 10 Hz, une habituation qui resserre les seuils quand le joueur reste à distance et qui se perd si on brusque le sujet. Le choix d'abort du decorator a été tranché par la mesure, pas par la doctrine — 1308 cm de fuite avec l'un, 2060 cm avec l'autre, pour un critère à 1500",
        "Assise contextuelle : le joueur peut s'asseoir partout où la géométrie le permet, à n'importe quelle hauteur — pas sur une liste de paliers. Le domaine est proportionnel à la taille du personnage, lue sur sa capsule de collision : un rebord de 80 cm est un siège pour un adulte et un mur pour un enfant",
        "Combat à deux mains avec des règles d'input distinctes par touche, IA de combat en machine à états C++ réutilisée par héritage sur plusieurs archétypes, et un système de puzzle interrupteurs → porte générique, instancié par script pour n'importe quelle séquence plutôt que codé en dur",
        "EvalHarness — dix scénarios qui notent le comportement de l'agent IA lui-même, chacun reproduisant avec des outils factices un piège réellement documenté dans l'historique du projet. L'agent reçoit une tâche ambiguë, un outil piégé et un outil fiable ; sa trajectoire est notée : a-t-il pris le bon outil, et sa conclusion est-elle fondée sur ce qu'il a vérifié plutôt que supposé",
        "Le harnais tourne en gate CI à chaque modification des règles du projet, avec un seuil de passage qui fait échouer le build — et les règles injectées dans l'éval sont extraites du fichier de règles réel, donc une règle qui change là-bas est suivie sans duplication. Les points d'entrée qui comptent exposent des spans OpenTelemetry (durée, verdict, compteurs de régression) plutôt que des lignes de log à recompter à la main",
      ],
      sections: [
        { title: "Un assistant qui tourne en local", text: "Un modèle de 14 milliards de paramètres sur une carte de 12 Go ne raisonne pas comme un grand modèle en ligne : il se trompe plus, invente des API et annonce volontiers un succès. L'assistant compense par le code. Les vraies signatures et les vrais chemins d'assets lui sont mis sous les yeux avant qu'il réponde, une question n'est jamais traitée comme un ordre, chaque modification attend un accord, et une réponse qui déclare « le PNJ est prêt » juste après une erreur d'outil est interceptée. Sur des tâches cadrées — écrire un script Unreal, créer un PNJ, régler une scène — il est utilisable au quotidien, sans coût." },
        { title: "Une contrainte qui force l'outillage", text: "Le projet interdit de piloter l'écran. Tout doit être scriptable — et c'est en s'y tenant qu'on découvre ce qui manque vraiment. Construire un Behavior Tree par script a buté sur une limite réelle : ni l'API Python d'Unreal ni l'outillage Blueprint existant ne savent éditer le graphe d'un Behavior Tree, seulement des Blueprints classiques. BTAuthoringKit comble exactement ce trou. Vérifier un comportement en jeu a buté sur une autre limite : le pawn joueur ne consomme pas l'input Blueprint standard, et l'injection Enhanced Input directe est inatteignable depuis Python. La bibliothèque d'input scripté ne fait qu'une chose — obtenir l'instance qui manquait — et l'input entre ensuite au même point qu'une vraie touche." },
        { title: "Vérifier la géométrie hors moteur", text: "Le noyau géométrique de l'outil de blockout ne référence aucun type Unreal. Une centaine de lignes de doublures suffisent donc à le compiler et à l'exercer en dehors de l'éditeur : une passe de 40 000 contours prend une seconde, là où un rebuild du plugin demande de fermer l'éditeur et deux minutes. Le harnais compile les fichiers du projet, pas des copies — si la géométrie se met à utiliser un type Unreal absent des doublures, il ne compile plus et on le sait immédiatement. Ce qui est vérifié n'est pas une liste de résultats attendus mais des propriétés qui doivent tenir pour n'importe quelle entrée." },
        { title: "Vérifier le comportement, pas l'état des données", text: "Un log vide ne prouve pas qu'un arbre ne tourne pas ; un decorator présent dans un asset ne prouve pas qu'il agit. Le test de non-régression pilote donc une vraie session de jeu et interroge l'état runtime — arbre en cours, valeurs du Blackboard, position, montage d'animation actif. Il existe parce que trois régressions d'une même journée auraient toutes été attrapées en une minute par ce test, et ont à la place coûté une session entière : la vérification portait sur l'état des données, jamais sur le comportement réel." },
        { title: "Et l'agent lui-même", text: "Le dernier angle mort était plus en amont : rien ne garantissait que l'agent qui pilote tout ça respecte les règles que le projet lui impose. Documenter une règle après un incident répare le passé ; elle ne protège pas contre la fois suivante, avec une tâche formulée autrement. Dix scénarios reproduisent donc, avec des outils factices, des pièges réellement rencontrés — un screenshot périmé face à une capture fraîche, une compilation réussie prise pour une vérification de gameplay — et notent la trajectoire de l'agent. Le tout en gate CI, parce qu'une procédure non vérifiable finit par ne pas être suivie." },
      ],
    },
    "rainbow-ant": {
      title: "Gameplay UE5", subtitle: "Rainbow Ant Studio", type: "Action-Aventure", role: "Gameplay Programmer",
      description: "Mission freelance d'un an comme Gameplay Programmer sur un jeu d'action-aventure. Mécaniques du personnage, natation, météo dynamique, map interactive.",
      highlights: ["Mécaniques de personnage complètes (déplacement, interactions, physique)", "Système de natation avec transitions surface/sous-eau", "Intégration météo dynamique (pluie, brouillard, vent)", "Map interactive avec zones de déclenchement", "Animations via State Machines et Blend Spaces"],
      sections: [],
    },
    "cs-group": {
      title: "Simulateur Aéronautique", subtitle: "CS Group — Défense", type: "Simulation Défense", role: "Technicien Systèmes Embarqués",
      description: "Simulateurs aéronautiques Inscape VTS pour un programme de défense nationale, 14 mois chez CS Group. Scénarios d'entraînement temps réel sous exigences fonctionnelles strictes et validation formelle, en lien direct avec ingénieurs systèmes et pilotes. Environnement défense réglementé, documentation classifiée : aucun détail ni visuel du programme n'est publié ici.",
      highlights: ["Conception et intégration de scénarios d'entraînement temps réel, sous exigences fonctionnelles strictes et validation formelle", "Développement en architecture modulaire", "Correction de bugs complexes sur des comportements simulés difficiles à reproduire", "Travail direct avec ingénieurs systèmes et pilotes, en environnement défense réglementé"],
      sections: [],
    },
    "time-restore": {
      title: "Time Restore", subtitle: "Projet personnel — UE4 → UE5", type: "RPG", role: "Développeur / Game Designer",
      description: "RPG à la 3e personne dans un monde fantaisiste où le temps s'est arrêté. Le joueur doit découvrir pourquoi et remettre le temps en marche pour sauver les habitants.",
      highlights: ["Conception d'une île fantaisiste avec biomes variés (lac, village, désert...)", "Système de quêtes avec journal d'objectifs et progression narrative", "Migration du projet UE4 vers UE5", "Level design de la map principale", "Système d'interaction PNJ"],
      sections: [
        { title: "Monde & Biomes", text: "L'île est découpée en plusieurs biomes : plaines, swamp, désert, cavernes, montagnes enneigées et île du volcan. Chaque zone a ses propres assets, ennemis et quêtes." },
        { title: "Gameplay & Systèmes", text: "Système de quêtes avec journal d'objectifs, interactions PNJ, crafting et combat à la 3e personne." },
      ],
    },
    "virtual-badass": {
      title: "Virtual Badass", subtitle: "Projet de fin d'études — E-Artsup", type: "Boss Fight", role: "Développeur / Intégrateur / Game Designer",
      description: "Boss fight 3D en équipe de 6 sur 1 an pour la dernière année de bachelor. Le joueur incarne un mercenaire en armure futuriste qui affronte le boss.",
      highlights: ["Développement des systèmes de combat du personnage et du boss", "Level design de la zone tutoriel et de l'arène de boss", "Intégration d'animations et de VFX", "Gestion de projet en équipe de 6 sur 1 an"],
      sections: [
        { title: "Le Boss", text: "Le boss est un robot steampunk imposant. Il possède plusieurs phases d'attaque. L'arène force le joueur à utiliser toutes les mécaniques apprises." },
        { title: "Personnages", text: "Le joueur incarne un mercenaire en armure futuriste avec Buck son compagnon robot. Les deux modèles ont été intégrés avec leurs animations complètes." },
      ],
    },
    "sheeplone": {
      title: "Sheeplone", subtitle: "Projet de fin d'année — 2 mois", type: "FPS / Survie", role: "Développeur / Game Designer",
      description: "Jeu FPS dans un monde fantaisiste. On incarne un magicien aventurier propulsé dans un monde par une entité maléfique, qui doit trouver le moyen de rentrer chez lui.",
      highlights: ["Développement du controller FPS et des mécaniques de magie", "IA ennemie : Mouton de Feu et Golem Gardien avec comportements distincts", "Système de quêtes avec journal d'objectifs", "Level design open-world fantaisiste"],
      sections: [
        { title: "Monde & Environnement", text: "Un monde fantaisiste ouvert avec plusieurs biomes. Le level design guide le joueur à travers les zones de quêtes." },
        { title: "Ennemis & IA", text: "Deux types d'ennemis : le Mouton de Feu (rapide, attaque directe) et le Golem Gardien (lent, puissant, zone de défense)." },
      ],
    },
    "aigyptos": {
      title: "Aigyptos", subtitle: "Ludum Dare 50 — 4 jours", type: "Survie / Stealth", role: "Développeur solo",
      description: 'Survival stealth 3D réalisé en 4 jours pour la Ludum Dare 50, thème "Retarder l\'inévitable". Une momie s\'échappe de sa pyramide sans se faire repérer.',
      highlights: ["Développement solo complet en 4 jours (game jam)", "IA de détection des archéologues (vision en cône, alerte, poursuite)", "Level design de la pyramide avec multiples chemins", "Concept art du personnage Aigys"],
      sections: [
        { title: "Level Design", text: "La pyramide est un labyrinthe multi-niveaux avec des gardes patrouillant des couloirs. Le joueur utilise les angles morts pour se faufiler jusqu'à la sortie." },
        { title: "Personnage & Direction Artistique", text: "Aigys est une momie égyptienne stylisée. Le concept art a guidé le modèle 3D pour rester cohérent avec l'univers graphique." },
      ],
    },
    "casse-brique": {
      title: "Casse-Brique", subtitle: "Défi école — 2 semaines", type: "Jeu Casual", role: "Développeur",
      description: "Casse-brique 2D en 10 niveaux. Le joueur incarne un chevalier détruisant des monstres pour sauver sa princesse. Réalisé en 2 semaines.",
      highlights: ["IA ennemie et comportements des blocs", "Calcul de trajectoire de balle avec rebonds physiques", "Blocs spéciaux : Bloc Explosif, Bloc Renforcé", "10 niveaux avec progression de difficulté"],
      sections: [
        { title: "Niveaux", text: "10 niveaux avec progression de difficulté croissante. Les premiers servent de tutoriel, les derniers introduisent des combinaisons de blocs spéciaux." },
        { title: "Blocs & IA", text: "Trois types de blocs : standard, Bloc Armure (résistant) et Bloc Explosif (détruit les adjacents). Chaque bloc a son IA de réaction." },
      ],
    },
  },
  en: {
    "comptoir": {
      title: "Comptoir & Bordereau",
      subtitle: "Two travel-agency tools with the language model kept on a leash — Personal project",
      type: "Software / Applied AI",
      role: "Solo developer",
      description: "A travel customer phrases their request the way they'd say it on the phone; Comptoir returns the holidays that genuinely match, with the real price for that family composition — and when nothing matches, it names the criterion to relax rather than offering something approximate. The language model understands the request and writes the answer; it decides nothing. Everything verifiable is settled in Python. Bordereau applies the same rule to hoteliers' emails: it turns them into one line per booking, and the model produces no value there — it only points, among the candidates already found in the email, to the one that belongs to the booking.",
      highlights: [
        "A strict split between what the model does (understand the sentence, write the answer) and what the code does: prices, dates, room capacity, board type and departure airport are settled in Python, by comparison — no model is ever asked whether €3,293 fits a €3,000 budget",
        "Every sentence in the answer is tied by the model to a specific field of a specific record, then re-checked against that record before display: a record never shown to the model, a field that doesn't exist, or a price that doesn't match the amount actually computed is dropped and logged, never shown to the customer",
        "When nothing matches, the model isn't called at all — the engine itself names the criterion to relax, in the order an agent actually negotiates: budget first, then dates, destination last",
        "The same filtering ported to SQLite (a single parameterised query with EXISTS over normalised tables) and compared record by record and price by price against the Python implementation on the same 20 requests — the port isn't assumed correct because it looks like the original, it's verified against it",
        "167 tests, including hard-constraint checks re-implemented by hand rather than by calling the engine's own functions: a test that checks the code with the code under test only confirms that the function agrees with itself",
        "Measured under real conditions with the model in the loop across 20 requests: extraction 20/20, correct abstention 8/8 on unsolvable cases, mean traceability 0.86 — with rejection reasons recorded, which is what separates a model that invents from a model that merely stumbles",
        "Context carry-over: \"same thing but no more than €3,000\" doesn't start from scratch. The model still only ever sees the latest sentence; the code carries forward, field by field, whatever that sentence doesn't mention. Abstention went from 6/8 to 8/8 after this fix",
        "The core depends on the Python standard library alone. The web interface (FastAPI) lives in a separate requirements file so as not to break that rule, and a Spring Boot facade (JDK 17) exposes the service over HTTP with request validation",
        "Three defects found only by measuring or by using it, never by re-reading: answers truncated by the context window, the model looping on repetition in list output, and an automatic criteria carry-over that made two unrelated requests accumulate from the second try onwards",
        "Bordereau — reads emails from hoteliers and ground handlers (around ten fields per booking: hotel, dates, rooms, price, contact). The target error isn't invention but misattribution: a real price attached to the wrong hotel, which a \"does this value appear in the email?\" check lets through",
        "Bordereau — closed lists (a hotel must come from the reference list), provenance kept for every value, and a model that may only answer a candidate number or null: it can neither invent nor fill a genuine gap. Measured with gemma4:12b running locally on 20 trap emails: 98.5% of fields found, 100% correctly attached (263/263), all 33 unanswerable fields left empty, 9 out of 9 uncertainties flagged",
        "Bordereau — the measurement was validated before the extractor, on fake extractors with known defects: the one that swaps hotels scores 100% of fields found and only 75% on hotel_id, hence the per-field breakdown. A web page highlights in the email the exact spot each value was read from, corrections grow the test set without the tool ever learning behind its users' backs, 50 tests with no network",
      ],
      sections: [
        { title: "The model understands, the code decides", text: "In travel, a hallucination isn't a curiosity: it's a customer arriving at a hotel without the kids' club they were promised. The language model is therefore confined to two jobs — turning a free sentence into a structured request, and writing the final answer. Everything checkable is settled in Python, by comparison. The model's own output isn't taken at face value either: JSON can arrive wrapped in markdown fences, truncated, or carrying a board type that doesn't exist in the catalogue — anything invalid is discarded, never guessed, and reported as unspecified." },
        { title: "Checked claim by claim", text: "The answer isn't written as free text: the model only sees the records already retained by the filter, and must return JSON where every sentence explicitly cites a field of a specific record. A verifier then looks each claim up in the record it cites and removes anything that doesn't match. In one measurement run, 12 claims out of 63 were dropped — none for contradicting a record, all for having been announced and then left empty." },
        { title: "The same engine, twice", text: "The criteria that reduce to set membership were rewritten in SQLite, in a single parameterised query. Period and price stay in Python — a date-range intersection and a child discount have no place in a WHERE clause without becoming unreadable. A test recomposes the full result and checks that it is identical, record by record and price by price, to the Python engine's output on the same requests." },
        { title: "Bordereau: checking the link, not the presence", text: "On an email carrying three hotels, four prices and two arrival dates, a model invents nothing: it crosses two bookings. Bordereau therefore splits the email into blocks around booking references and only looks for a value inside its own block — without any model, 96% of fields are found and none is misattributed. The model only steps in on the fields left empty, one at a time, and can only answer a number among the candidates shown. Its only possible mistake is therefore exactly the one the measurement breaks down field by field." },
      ],
    },
    "claude-ue5": {
      title: "Driving & verifying a 3D engine",
      subtitle: "C++, Python, CI — AI-driven Unreal Engine 5 plugin, 117 tests — Personal project",
      type: "Tool / AI",
      role: "Solo developer",
      description: "C++ plugin and MCP bridge for building 3D scenes in Unreal Engine 5 by script, driven by a conversational AI. Nothing is saved without verification: 117 automated tests re-run on every change (6 of them in continuous integration), collision checks, screenshots and automated playtesting.",
      highlights: [
        "MCP bridge (Remote Execution API) that lets an external agent (Claude Code / Claude Cowork) drive the UE5 editor in natural language — level generation, gameplay mechanics, automatic verification of its own work",
        "Dockable C++ Slate panel (Tools → Claude AI) natively embedded in the editor, for local use without depending on an external tool",
        "117 automated tests (111 in-editor + 6 in GitHub Actions CI) validating every plugin change before it's accepted — no silent regressions",
        "Autonomous playtest agent: discovers its own route on any level (interactive objectives, enemies, NavMesh coverage, no hard-coded coordinates), drives the character in-game (PIE) and logs events (enemy detection, stuck states, jumpscares) — found and helped fix a real bug preventing enemies from chasing the player",
        "trust_gate: file integrity is checked rather than assumed — several independent access channels each record a SHA-256 of the same file, and a TRUSTED / DIVERGENT verdict only comes from comparing them. Caught real stale or truncated files that raised no error anywhere",
        "BatchWireGraph: a JSON DSL that wires an entire Blueprint graph (nodes + connections) in a single call instead of 20+ individual API calls",
        "Zero-overlap placement (safe_spawn_enemy): occupancy grid + floor raycast + real physics check — an actor that would land inside a wall gets repositioned automatically, never committed as-is",
        "Non-regressive visual verification (block-based SSIM): every approved zone becomes a reference image; future rebuilds are compared to catch silent drift (a moved light, a swapped material)",
        "100% open source, GitHub Actions CI on every commit — 25 undocumented UE5.7 API quirks identified and worked around (see docs/KNOWN_ISSUES.md)",
      ],
      sections: [
        { title: "Two Ways to Drive the Editor", text: "An MCP bridge (Remote Execution API) lets an external agent like Claude Code or Claude Cowork drive the UE5 editor from a plain conversation. A dockable C++ Slate panel (Tools → Claude AI) offers the same kind of Python execution directly inside the editor, with no external dependency." },
        { title: "Verification Before Every Save", text: "Nothing is accepted blindly: verify_level.py automatically scans for colliding actors, misconfigured lights, and an unbuilt NavMesh; a synchronous screenshot (working around a UE5 rendering bug) allows a systematic visual review before any save()." },
        { title: "Autonomous Playtest Agent", text: "A dedicated module drives the player character in PIE via waypoints and real NavMesh pathfinding, logs gameplay events (detection, chase, jumpscare), and lets a scenario be replayed reproducibly — this agent is what surfaced a real enemy-behaviour bug invisible to static testing." },
        { title: "BlueprintEditingSubsystem & Anti-Regression Suite", text: "BlueprintEditingSubsystem exposes a C++ API to wire entire Blueprint graphs in a single call (BatchWireGraph DSL). Before and after any plugin change, a 117-test suite revalidates every subsystem — a regression is caught before it ever reaches the level." },
      ],
    },
    "level-design-tools": {
      title: "Automated test bench — 3D tool",
      subtitle: "C#, Unity 6 — 40,000 cases verified, 21 injected faults, 4 real bugs found — Personal project",
      type: "Testing / Verification",
      role: "Solo developer",
      description: "A 3D editor tool (Unity) and, above all, the test bench that verifies it: 40,000 cases run in a few seconds, where each case used to need a manual try in the editor. The bench's own reliability is measured by injecting 21 deliberate faults — 19 caught — and it found 4 real bugs in code that compiled and appeared to work.",
      highlights: [
        "Room Builder: three editor modes — a parametric room, an outline drawn in the Scene view then extruded with the height following the cursor (Ctrl snaps to the grid, the gesture sets the direction), and opening cuts made directly on the hovered surface",
        "Cutting removes no matter: the panel keeps its logical description (outline, thickness, list of holes) on a serialised component and its mesh is fully regenerated every time — a wall stays cuttable indefinitely, every opening is undoable",
        "Geometry with no dependency on the Unity API: it compiles and runs outside the editor, which is what makes exercising 40,000 panels in seconds possible instead of a round trip through Unity for every attempt",
        "14 properties checked rather than fixed expected results — area conservation, exact coverage (a point in the material covered by exactly one triangle, a point in a hole by none), watertightness of the prism, volume equal to area × thickness, scale independence, determinism",
        "Hand-rolled mutation testing: 21 plausible defects injected one at a time into the geometry code, recompiled, put through the battery — 19 caught. The figure started at 67%, and each step up was earned by writing the property that was missing",
        "Four real bugs found in code that compiled and worked on screen: an absolute threshold making the mesh depend on the wall's position in the level, an extrapolation placing a vertex inside a neighbouring hole (1 case in 1,500), a 15 µm crack between a face and its edge, and a cylinder accepted as a box",
        "Layered verification — compiler, out-of-engine properties, a live probe into the editor over MCP, human eye: each catches a class of defect the others structurally cannot see. The cylinder could only be found by querying Unity live",
        "Mutation testing also surfaced 137 lines of dead code: an injected defect that survives without explanation often hits code nothing depends on any more",
        "Three false alarms from the harness itself, diagnosed and fixed on the test side: calibrating properties against the code's real contract (a vertex 1.6 µm from a 2.7 m edge is not on it) is a good share of the work — a harness that cries wolf is abandoned in three days",
      ],
      sections: [
        { title: "Three blockout modes", text: "Box mode produces a rectangular room from dimensions. Free-draw mode lets you click an outline in the Scene view: once closed, the height follows the mouse until the confirming click, Ctrl snaps to the grid, and dragging below the drawing plane extrudes downwards. Cut mode pierces an opening — door, window, floor hatch — directly on the hovered surface. Cutting accepts any flat extruded outline, including a box that came from elsewhere; a cylinder or a sphere is refused with the reason, because reconstruction would replace them with a box." },
        { title: "Properties, not fixed results", text: "Triangulation and 3D assembly depend on no Unity API — around a hundred lines of stand-ins for Vector2, Vector3 and Mathf are enough. The harness therefore compiles the project's own files, not copies, and exercises them outside the editor. What is checked is not a list of expected results but properties that must hold for any input. Randomly generated cases are complemented by pinned regressions — each is a defect that genuinely existed, and each was watched failing on the version that carried it." },
        { title: "Measuring what the verification is worth", text: "A passing test battery says nothing about what it would catch. The mutation harness injects 21 plausible defects, one at a time, and counts how many the battery catches: 19 out of 21. The two survivors hit code nothing depends on. The figure started at 67% — the properties added since exist because an injected defect slipped through unseen, not because they seemed like a good idea." },
      ],
    },
    "horror-ue5": {
      title: "Horror Project", subtitle: "First-person horror game — Personal project", type: "Horror", role: "Solo developer",
      description: "Solo first-person horror game in Unreal Engine 5.7. The player crosses rooms haunted by mannequins that move as soon as they're no longer lit: the flashlight is both the only defence and the only way to see. To win, reach the last zone and flip the switch. The levels were built and verified with my AI Agent × UE5 toolchain.",
      highlights: [
        "Mannequin AI as a Behavior Tree (lit → stunned → chase → patrol) with AI Perception: an enemy caught in the flashlight beam stops, and resumes the hunt the moment it leaves the light",
        "Complete game loop: flashlight pickup, proximity-triggered jumpscares, a final switch that removes the enemies and starts the win sequence, and a main menu overlaid on the paused level",
        "Several playable levels, including HorrorLevel (9 zones and corridors) and SanatoriumLevel, an \"isolation and madness\" level built end to end, then played through to victory by the playtest agent",
        "Atmosphere tuned for horror: Lumen GI turned off for hard shadows, manual exposure, vignette, grain and desaturation, a four-light composition per room, flickering neons",
        "Red vignette driven from C++ (VignetteManager) when an enemy sees the player while unlit",
        "Real bug found by the playtest agent: perception was disabled on every enemy's component template, so no chase could ever start — invisible to any static check, fixed and re-verified in game",
      ],
      sections: [],
    },
    "hover-ue5": {
      title: "HoverCharacter UE5", subtitle: "Procedural hover character — Personal project", type: "Gameplay / Physics", role: "Solo developer",
      description: "C++ character system in UE5.8 combining standard walking and hover mode, with banking, surface alignment and slope acceleration. Procedurally generated desert terrain in C++, and physics calibrated iteratively against reference hover-flight games for a credible feel.",
      highlights: [
        "C++ HoverCharacter — dual walk/hover mode with dynamic banking, trace-based surface alignment and slope acceleration derived from the ground normal",
        "Procedural desert terrain (ADesertTerrain) via ProceduralMeshComponent — 5 Perlin noise octaves, dynamic LOD",
        "Iterative physics calibration against reference flight games with a similar hover mechanic, to reach a credible feel rather than arbitrary tuning values",
        "Documented workaround for a UE5.7/5.8 bug (Enhanced Input modifiers not persisting between sessions) via IsInputKeyDown() with explicit AZERTY mapping — the same fix later re-applied on a second project (see 3rd-person RPG)",
      ],
      sections: [
        { title: "HoverCharacter — Dual Mode C++", text: "The character switches between standard walking (capsule + CharacterMovementComponent) and hover mode (levitation, lateral banking, surface alignment via trace). Slope acceleration is derived from the ground normal vector — the steeper the slope, the stronger the boost." },
        { title: "Procedural Terrain & Physics Calibration", text: "ADesertTerrain generates a desert landscape in C++ via ProceduralMeshComponent using 5 Perlin noise octaves. Hover physics were calibrated iteratively against reference games with a similar flight mechanic, to reach a feel consistent with player expectations." },
        { title: "Enhanced Input Bug Workaround (UE5.8)", text: "Documented bug: Enhanced Input modifiers (deadzone, swizzle, etc.) do not persist between PIE sessions in UE5.7/5.8. Solution: replaced by IsInputKeyDown() on critical axes with explicit AZERTY mapping. Reproducible, documented, and already reused on a follow-up project." },
      ],
    },
    "assistant-ue5-local": {
      title: "Local AI Assistant × UE5",
      subtitle: "An assistant driving Unreal Engine 5.8 in natural language, fully local, and the tooling of the GameAnimationSample project — Personal project",
      type: "Tool / Local AI",
      role: "Solo developer",
      description: "A natural-language assistant that drives Unreal Engine 5.8 while running entirely on my graphics card: no account, no subscription, no connection once installed. Its playground is GameAnimationSample, around which were built four Unreal Engine 5.8 plugins and an evaluation harness, held together by one constraint kept from beginning to end: nothing is driven through the screen. Everything — building a level, wiring a Behavior Tree, playing a session to check a behaviour — has to go through script. That constraint is what forced the missing tools to be written, then verified against what they claim to do, and finally what forced checking that the agent using them follows the project's own rules.",
      highlights: [
        "Local UE5 assistant — Qwen2.5-Coder 14B via Ollama on an RTX 4070, with a home-made agent loop and MCP client plugged into the Unreal servers (including the project's own: NPCs, Behavior Trees, playtesting). No Internet connection once installed",
        "RAG built from the editor itself: 14,572 methods of the UE 5.8.2 Python API and 3,931 project assets with their real paths, so the model stops inventing functions and paths that don't exist. Project conventions injected into every message, situational rules served only when they concern the question",
        "Safeguards in code rather than trust in the model: confirmation before any tool that modifies the project (a sentence in reply redirects the model), tool calls written as text executed only if the tool really exists, a time cap on every MCP call, a failure log, and no way to announce success after a tool failure — 22 test scripts with a fake model, no Unreal needed",
        "BlockoutTools — a Slate level-design tool for UE5.8: a parametric room, an outline drawn in the viewport then extruded live (Ctrl constrains to right angles, Ctrl+F closes square), and door and window cuts on the hovered surface. The panel ships to someone who doesn't program, with a three-minute install sheet and a status line that always explains what happened",
        "BlockoutTools' geometry depends on no Unreal API — around a hundred lines of stand-ins are enough to compile it outside the engine. The harness therefore exercises the project's own files, not copies: 40,000 outlines in one second, against a plugin rebuild (editor closed, ~2 min) plus a round trip through the editor",
        "Properties rather than fixed results: triangulated area equal to the outline's area minus its holes, exact coverage, a double-sided prism of the right thickness, a degeneracy threshold relative to panel size, no T-junctions, bit-for-bit determinism",
        "A bug in the harness itself, found before it was ever used: the outline generator drew uniform angles then sorted them, which only yields a simple polygon when the vertices go round the centre — 57 self-intersecting outlines out of 2,000 were being blamed on the code under test. Two thresholds also had to be recalibrated against the code's real contract rather than against intuition",
        "BTAuthoringKit — a C++ plugin exposing a scriptable API to build complete Behavior Trees (Blackboard, composites, tasks, decorators, services, visual graph included) without ever opening the graph editor. Written because neither Unreal's Python API nor the existing Blueprint tooling can edit a Behavior Tree graph",
        "Input injected at the same point as a real key press: it goes through the Input Mapping Context, the modifiers and the triggers. Measured in a real play session, 1,037 cm covered in 4 s. That is what makes behavioural verification possible without ever driving the screen — both natural routes being dead, each for a distinct reason",
        "A regression test that drives a play session on its own (~52 s of game time) and checks seven points by real behaviour rather than by data state: tree running, single controller, movement, sitting animation, detection through real perception, closing in on the player, no frozen NPC",
        "NPC AI with tolerance and habituation: three attention levels written to the Blackboard at 10 Hz, and a habituation that tightens the thresholds while the player keeps their distance and is lost by rushing the subject. The decorator's abort mode was settled by measurement, not doctrine — 1,308 cm of flight with one, 2,060 cm with the other, against a 1,500 cm criterion",
        "Contextual sitting: the player can sit anywhere the geometry allows, at any height — not on a list of preset steps. The domain is proportional to the character's size, read from its collision capsule: an 80 cm ledge is a seat for an adult and a wall for a child",
        "Two-handed combat with distinct input rules per key, combat AI as a C++ state machine reused through inheritance across several archetypes, and a generic switch → door puzzle system instantiated by script for any sequence rather than hard-coded",
        "EvalHarness — ten scenarios grading the AI agent's own behaviour, each reproducing with mock tools a pitfall genuinely documented in the project's history. The agent is given an ambiguous task, a trapped tool and a reliable one; its trajectory is then graded: did it reach for the right tool, and is its conclusion grounded in what it verified rather than assumed",
        "The harness runs as a CI gate on every change to the project's rules, with a pass threshold that fails the build — and the rules injected into the eval are extracted from the real rules file, so a rule that changes there is followed without duplicated text. The entry points that matter expose OpenTelemetry spans (duration, verdict, regression counters) instead of log lines to be counted by hand",
      ],
      sections: [
        { title: "An assistant that runs locally", text: "A 14-billion-parameter model on a 12 GB card doesn't reason like a large online model: it makes more mistakes, invents APIs and happily reports success. The assistant makes up for it in code. Real signatures and real asset paths are put in front of it before it answers, a question is never treated as an order, every modification waits for approval, and a reply claiming \"the NPC is ready\" right after a tool error is intercepted. On well-scoped tasks — writing an Unreal script, creating an NPC, tuning a scene — it is usable day to day, at no cost." },
        { title: "A constraint that forces the tooling", text: "The project forbids driving the screen. Everything has to be scriptable — and holding to that is how you find out what is genuinely missing. Building a Behavior Tree by script hit a real limit: neither Unreal's Python API nor the existing Blueprint tooling can edit a Behavior Tree graph, only ordinary Blueprints. BTAuthoringKit fills exactly that gap. Checking a behaviour in game hit another: the player pawn doesn't consume standard Blueprint input, and direct Enhanced Input injection is unreachable from Python. The scripted input library does one thing only — obtain the instance that was missing — and the input then enters at the same point as a real key." },
        { title: "Verifying geometry outside the engine", text: "The blockout tool's geometry core references no Unreal type. Around a hundred lines of stand-ins are therefore enough to compile and exercise it outside the editor: a pass of 40,000 outlines takes a second, where a plugin rebuild means closing the editor and waiting two minutes. The harness compiles the project's own files, not copies — if the geometry starts using an Unreal type the stand-ins don't cover, it stops compiling and that is known immediately. What is checked is not a list of expected results but properties that must hold for any input." },
        { title: "Verifying behaviour, not data state", text: "An empty log doesn't prove a tree isn't running; a decorator present in an asset doesn't prove it acts. The regression test therefore drives a real play session and queries runtime state — tree running, Blackboard values, position, active animation montage. It exists because three regressions on a single day would all have been caught in a minute by this test, and instead cost a full session: the verification looked at data state, never at real behaviour." },
        { title: "And the agent itself", text: "The last blind spot sat further upstream: nothing guaranteed that the agent driving all this follows the rules the project imposes on it. Documenting a rule after an incident repairs the past; it does not protect against the next time, with the task phrased slightly differently. Ten scenarios therefore reproduce, with mock tools, pitfalls that were genuinely hit — a stale screenshot against a fresh capture, a successful compile taken for a gameplay check — and grade the agent's trajectory. All of it as a CI gate, because a procedure that cannot be verified ends up not being followed." },
      ],
    },
    "rainbow-ant": {
      title: "UE5 Gameplay", subtitle: "Rainbow Ant Studio", type: "Action-Adventure", role: "Gameplay Programmer",
      description: "One-year freelance mission as Gameplay Programmer on an action-adventure game. Character mechanics, swimming system, dynamic weather, interactive map.",
      highlights: ["Full character mechanics (movement, interactions, physics)", "Swimming system with surface/underwater transitions", "Dynamic weather integration (rain, fog, wind)", "Interactive map with trigger zones", "Animations via State Machines and Blend Spaces"],
      sections: [],
    },
    "cs-group": {
      title: "Aeronautical Simulator", subtitle: "CS Group — Defence", type: "Defence Simulation", role: "Embedded Systems Technician",
      description: "Inscape VTS aeronautical simulators for a national defence programme, 14 months at CS Group. Real-time training scenarios under strict functional requirements and formal validation, working directly with systems engineers and pilots. Regulated defence environment, classified documentation: no programme details or visuals are published here.",
      highlights: ["Designed and integrated real-time training scenarios under strict functional requirements and formal validation", "Modular software architecture", "Fixed complex bugs in hard-to-reproduce simulated behaviour", "Worked directly with systems engineers and pilots in a regulated defence environment"],
      sections: [],
    },
    "time-restore": {
      title: "Time Restore", subtitle: "Personal project — UE4 → UE5", type: "RPG", role: "Developer / Game Designer",
      description: "3rd-person RPG in a fantasy world where time has stopped. The player must discover why and restart time to save the inhabitants.",
      highlights: ["Fantasy island with varied biomes (lake, village, desert...)", "Quest system with objective journal and narrative progression", "Migration from UE4 to UE5", "Main map level design", "NPC interaction system"],
      sections: [
        { title: "World & Biomes", text: "The island is split into biomes: plains, swamp, desert, caverns, snowy mountains and volcano island. Each zone has its own assets, enemies and quests." },
        { title: "Gameplay & Systems", text: "Quest system with objective journal, NPC interactions, crafting and third-person combat." },
      ],
    },
    "virtual-badass": {
      title: "Virtual Badass", subtitle: "Final-year project — E-Artsup", type: "Boss Fight", role: "Developer / Integrator / Game Designer",
      description: "3D boss fight made by a team of 6 over 1 year for the final bachelor year. The player is a futuristic-armoured mercenary who must defeat the boss.",
      highlights: ["Character and boss combat systems", "Tutorial zone and boss arena level design", "Animation and VFX integration", "Project management in a 6-person team over 1 year"],
      sections: [
        { title: "The Boss", text: "The boss is an imposing steampunk robot with multiple attack phases. The arena forces the player to use every mechanic learned in the tutorial." },
        { title: "Characters", text: "Player character in futuristic armour with Buck the robot companion. Both models integrated with full animations." },
      ],
    },
    "sheeplone": {
      title: "Sheeplone", subtitle: "End-of-year project — 2 months", type: "FPS / Survival", role: "Developer / Game Designer",
      description: "FPS in a fantasy world. You play a wizard adventurer thrust into an unknown world by a dark entity, who must find a way home.",
      highlights: ["FPS controller and magic mechanics", "Enemy AI: Fire Sheep and Golem Guardian with distinct behaviours", "Quest system with objective journal", "Open-world fantasy level design"],
      sections: [
        { title: "World & Environment", text: "An open fantasy world with several biomes. Level design guides the player through quest areas." },
        { title: "Enemies & AI", text: "Two enemy types: Fire Sheep (fast, direct attack) and Golem Guardian (slow, powerful, area defender)." },
      ],
    },
    "aigyptos": {
      title: "Aigyptos", subtitle: "Ludum Dare 50 — 4 days", type: "Survival / Stealth", role: "Solo developer",
      description: 'Survival stealth 3D game made in 4 days for Ludum Dare 50, theme "Delay the Inevitable". A mummy escapes her pyramid without being spotted.',
      highlights: ["Full solo development in 4 days (game jam)", "Archaeologist detection AI (cone vision, alert, chase)", "Pyramid level design with multiple escape routes", "Aigys character concept art"],
      sections: [
        { title: "Level Design", text: "The pyramid is a multi-level labyrinth with patrolling guards. The player uses blind spots to sneak to the exit." },
        { title: "Character & Art Direction", text: "Aigys is a stylised Egyptian mummy. The concept art guided the 3D model to stay consistent with the visual world." },
      ],
    },
    "casse-brique": {
      title: "Brick Breaker", subtitle: "School challenge — 2 weeks", type: "Casual Game", role: "Developer",
      description: "2D brick breaker with 10 levels. You play a knight destroying monsters to save your princess. Built in 2 weeks.",
      highlights: ["Enemy AI and block behaviours", "Ball trajectory with physics bounces", "Special blocks: Explosive Block, Armoured Block", "10 levels with increasing difficulty"],
      sections: [
        { title: "Levels", text: "10 levels with increasing difficulty. Early levels serve as tutorials; later levels combine special blocks requiring strategy." },
        { title: "Blocks & AI", text: "Three block types: standard, Armour Block (resistant) and Explosive Block (destroys adjacent blocks). Each has its own reaction AI." },
      ],
    },
  },
};

const translations = {
  fr: {
    nav_about: "À propos",
    nav_experience: "Expérience",
    nav_projects: "Projets",
    nav_skills: "Compétences",
    nav_contact: "Contact",
    nav_cta: "Me contacter",

    hero_tag: "Disponible immédiatement — Toulouse",
    hero_subtitle: "Développeur logiciel C++ / C# · Simulation & systèmes embarqués",
    hero_desc: "Je développe des logiciels temps réel où une erreur ne doit pas passer en production, et je construis les tests automatiques qui le garantissent.",
    hero_btn_projects: "Voir mes projets",
    hero_btn_contact: "Me contacter",
    hero_btn_cv: "Télécharger mon CV",
    hero_stat1_num: "2 ans",
    hero_stat1_label: "Développement logiciel",
    hero_stat2_num: "14 mois",
    hero_stat2_label: "Simulation aéronautique — défense",
    hero_stat3_num: "C++ · C# · Python",
    hero_stat3_label: "Temps réel, tests automatisés",
    hero_stat4_num: "Habilitable",
    hero_stat4_label: "Nationalité française",

    about_label: "À propos",
    about_title: "Thomas\nLabetouille",
    about_p1: "Je développe des logiciels pour des systèmes temps réel où une erreur ne doit pas passer en production, et je construis les tests automatiques qui le garantissent. J'ai l'habitude de travailler avec des experts métier — ingénieurs systèmes, pilotes — pour transformer un besoin opérationnel en fonctionnement vérifié.",
    about_p2: "Chez CS Group, pendant 14 mois, j'ai conçu et intégré des scénarios d'entraînement temps réel sur des simulateurs aéronautiques (Inscape VTS) pour un programme de défense nationale : exigences fonctionnelles strictes, validation formelle, documentation classifiée. Avant cela, j'ai développé en C++ les mécaniques d'un personnage sur Unreal Engine 5 pour un studio, en freelance et à distance.",
    about_p3: "Un fil commun à mes projets : du code qui compile et qui a l'air de marcher n'est pas du code correct. Chacun embarque donc de quoi le vérifier — suites de non-régression, tests de propriétés, injection volontaire de défauts pour mesurer ce que valent les tests eux-mêmes, intégration continue.",
    about_p4: "Je suis basé à Toulouse, véhiculé, disponible immédiatement. Titulaire d'un Bachelor en développement (RNCP niveau 6, équivalent Bac+3).",
    about_card1_label: "Domaine",
    about_card1_val: "Logiciel temps réel, simulation & tests",
    about_card1_sub: "C++ / C# / Python",
    about_card2_label: "Expérience pro",
    about_card2_val: "2 ans",
    about_card2_sub: "dont 14 mois en simulation aéronautique défense",
    about_card3_label: "Disponibilité",
    about_card3_val: "Disponible immédiatement",
    about_card3_sub: "CDI · CDD · Prestation",
    about_card4_label: "Localisation",
    about_card4_val: "Toulouse, France",
    about_card4_sub: "Permis B, véhiculé · Habilitable",

    exp_label: "Expérience",
    exp_title: "Parcours\nprofessionnel",
    experience: [
      {
        role: "Technicien Systèmes Embarqués",
        company: "CS Group",
        type: "CDI",
        period: "Sept. 2024 — Nov. 2025",
        domain: "Simulation / Défense",
        color: "#ead6af",
        desc: "Simulateurs aéronautiques Inscape VTS pour un programme de défense nationale. Conception et intégration de scénarios d'entraînement temps réel sous exigences fonctionnelles strictes et validation formelle ; correction de bugs complexes sur des comportements simulés difficiles à reproduire ; travail direct avec ingénieurs systèmes et pilotes.",
      },
      {
        role: "Gameplay Programmer",
        company: "Rainbow Ant Studio",
        type: "Freelance",
        period: "Déc. 2023 — Sept. 2024",
        domain: "Jeu Vidéo / UE5",
        color: "#ead6af",
        desc: "Mission freelance sur un jeu d'action-aventure UE5. Systèmes gameplay complets : personnage, natation, météo, map interactive.",
      },
      {
        role: "Bachelor Développement de Jeux Vidéo",
        company: "E-Artsup",
        type: "Formation",
        period: "2020 — 2023",
        domain: "RNCP Niveau 6",
        color: "#ead6af",
        desc: "Spécialisation C# / Unity / Game & Level Design. Certification RNCP Niveau 6.",
      },
    ],

    proj_label: "Projets",
    proj_title: "Ce que j'ai\nconstruit",
    proj_group_engineering: "Ingénierie logicielle & vérification",
    proj_group_games: "Moteurs temps réel & jeu vidéo",
    proj_filter_all: "Tous",
    proj_filter_software: "Logiciel / IA",
    proj_details: "▼ Détails techniques",
    proj_details_close: "▲ Réduire",
    proj_see: "↗ Voir le projet",
    proj_featured: "⚡ Projet phare",
    proj_placeholder: "Images à venir",
    status_completed: "✓ Terminé",
    status_ongoing: "◐ En cours",

    skills_label: "Compétences",
    skills_title: "Stack &\nsavoir-faire",
    skills: [
      { category: "Langages", items: ["C++ (principal)", "C#", "Python", "Java", "SQL"] },
      { category: "Tests & fiabilité", items: ["Tests automatisés", "Non-régression", "Tests de propriétés", "Mutation testing", "Intégration continue (GitHub Actions)", "pytest"] },
      { category: "Simulation & 3D", items: ["Inscape VTS", "Temps réel", "Scénarios d'entraînement", "Unreal Engine 5", "Unity 6", "Physique & comportements simulés"] },
      { category: "Architecture", items: ["Architecture modulaire", "Débogage de comportements complexes", "Exigences fonctionnelles", "Documentation technique"] },
      { category: "IA appliquée", items: ["LLM en local (Ollama)", "MCP (Model Context Protocol)", "Extraction structurée", "Vérification des réponses de modèle"] },
      { category: "Back-end", items: ["FastAPI", "Spring Boot (JDK 17)", "SQLite / SQL", ".NET 8"] },
      { category: "Outils", items: ["Git / GitHub", "Perforce", "Plastic SCM"] },
      { category: "Savoir-être", items: ["Travail avec experts métier et pilotes", "Environnement réglementé défense", "Autonomie", "Anglais technique"] },
    ],

    contact_label: "Contact",
    contact_title: "Parlons de\nvotre besoin",
    contact_intro: "Disponible immédiatement en CDI, CDD ou prestation.\nToulouse et alentours, véhiculé.\nSimulation, logiciel temps réel et embarqué, tests et validation.",
    contact_email_label: "Email",
    contact_linkedin_label: "LinkedIn",
    contact_github_label: "GitHub",
    contact_github_value: "ThomasLabetouille",
    contact_cv_label: "CV",
    contact_cv_value: "Télécharger mon CV",
    contact_cv_file: "/CV_Thomas_Labetouille_FR.pdf",
    footer: "Développeur logiciel C++ / C# · Toulouse, France",

    detail_back: "← Retour aux projets",
    detail_role: "Rôle",
    detail_engine: "Moteur",
    detail_year: "Année",
    detail_highlights: "// Ce que j'ai développé",
    detail_tech: "Technologies",
    detail_itch: "↗ Télécharger sur itch.io",
    detail_all: "← Tous les projets",
    detail_prev: "← Projet précédent",
    detail_next: "Projet suivant →",

    gallery_claude_panel: "Panneau Claude AI dans l'éditeur UE5",
    gallery_claude_level: "Level design procédural généré par l'agent",
    gallery_claude_python: "Exécution Python temps réel depuis le chat",
    gallery_claude_blueprint: "Édition de Blueprint via BatchWireGraph",
  },

  en: {
    nav_about: "About",
    nav_experience: "Experience",
    nav_projects: "Projects",
    nav_skills: "Skills",
    nav_contact: "Contact",
    nav_cta: "Contact me",

    hero_tag: "Available now — Toulouse, France",
    hero_subtitle: "C++ / C# Software Developer · Simulation & embedded systems",
    hero_desc: "I build real-time software where an error must not reach production, and the automated tests that make sure it doesn't.",
    hero_btn_projects: "View my projects",
    hero_btn_contact: "Contact me",
    hero_btn_cv: "Download my resume",
    hero_stat1_num: "2 years",
    hero_stat1_label: "Software development",
    hero_stat2_num: "14 months",
    hero_stat2_label: "Aeronautical simulation — defence",
    hero_stat3_num: "C++ · C# · Python",
    hero_stat3_label: "Real-time, automated testing",
    hero_stat4_num: "Clearable",
    hero_stat4_label: "French citizen",

    about_label: "About",
    about_title: "Thomas\nLabetouille",
    about_p1: "I build software for real-time systems where an error must not reach production, and the automated tests that guarantee it. I'm used to working with domain experts — systems engineers, pilots — to turn an operational need into verified behaviour.",
    about_p2: "At CS Group, for 14 months, I designed and integrated real-time training scenarios on aeronautical simulators (Inscape VTS) for a national defence programme: strict functional requirements, formal validation, classified documentation. Before that, I developed character mechanics in C++ on Unreal Engine 5 for a studio, freelance and fully remote.",
    about_p3: "One thread runs through my projects: code that compiles and appears to work is not correct code. Each one ships with the means to verify it — regression suites, property-based tests, deliberately injected faults to measure what the tests themselves are worth, continuous integration.",
    about_p4: "Based in Toulouse, with a car, available immediately. Bachelor's degree in development (RNCP Level 6).",
    about_card1_label: "Field",
    about_card1_val: "Real-time software, simulation & testing",
    about_card1_sub: "C++ / C# / Python",
    about_card2_label: "Pro experience",
    about_card2_val: "2 years",
    about_card2_sub: "incl. 14 months in defence aeronautical simulation",
    about_card3_label: "Availability",
    about_card3_val: "Available now",
    about_card3_sub: "Permanent · Fixed-term · Consulting",
    about_card4_label: "Location",
    about_card4_val: "Toulouse, France",
    about_card4_sub: "Driving licence, car · Clearable",

    exp_label: "Experience",
    exp_title: "Career\npath",
    experience: [
      {
        role: "Embedded Systems Technician",
        company: "CS Group",
        type: "Permanent",
        period: "Sep. 2024 — Nov. 2025",
        domain: "Simulation / Defence",
        color: "#ead6af",
        desc: "Inscape VTS aeronautical simulators for a national defence programme. Designed and integrated real-time training scenarios under strict functional requirements and formal validation; fixed complex bugs in hard-to-reproduce simulated behaviour; worked directly with systems engineers and pilots.",
      },
      {
        role: "Gameplay Programmer",
        company: "Rainbow Ant Studio",
        type: "Freelance",
        period: "Dec. 2023 — Sep. 2024",
        domain: "Game Dev / UE5",
        color: "#ead6af",
        desc: "Freelance mission on a UE5 action-adventure game. Full gameplay systems: character, swimming, weather, interactive map.",
      },
      {
        role: "Bachelor in Video Game Development",
        company: "E-Artsup",
        type: "Education",
        period: "2020 — 2023",
        domain: "RNCP Level 6",
        color: "#ead6af",
        desc: "Specialisation in C# / Unity / Game & Level Design. RNCP Level 6 certification.",
      },
    ],

    proj_label: "Projects",
    proj_title: "What I've\nbuilt",
    proj_group_engineering: "Software engineering & verification",
    proj_group_games: "Real-time engines & games",
    proj_filter_all: "All",
    proj_filter_software: "Software / AI",
    proj_details: "▼ Technical details",
    proj_details_close: "▲ Collapse",
    proj_see: "↗ View project",
    proj_featured: "⚡ Featured",
    proj_placeholder: "Images coming soon",
    status_completed: "✓ Completed",
    status_ongoing: "◐ Ongoing",

    skills_label: "Skills",
    skills_title: "Stack &\nexpertise",
    skills: [
      { category: "Languages", items: ["C++ (main)", "C#", "Python", "Java", "SQL"] },
      { category: "Testing & reliability", items: ["Automated testing", "Regression testing", "Property-based testing", "Mutation testing", "Continuous integration (GitHub Actions)", "pytest"] },
      { category: "Simulation & 3D", items: ["Inscape VTS", "Real-time", "Training scenarios", "Unreal Engine 5", "Unity 6", "Physics & simulated behaviour"] },
      { category: "Architecture", items: ["Modular architecture", "Debugging complex behaviour", "Functional requirements", "Technical documentation"] },
      { category: "Applied AI", items: ["Local LLMs (Ollama)", "MCP (Model Context Protocol)", "Structured extraction", "Model-output verification"] },
      { category: "Back-end", items: ["FastAPI", "Spring Boot (JDK 17)", "SQLite / SQL", ".NET 8"] },
      { category: "Tools", items: ["Git / GitHub", "Perforce", "Plastic SCM"] },
      { category: "Soft skills", items: ["Working with domain experts and pilots", "Regulated defence environment", "Autonomy", "Technical English"] },
    ],

    contact_label: "Contact",
    contact_title: "Let's work\ntogether",
    contact_intro: "Available now for permanent, fixed-term or consulting positions.\nToulouse area.\nSimulation, real-time and embedded software, testing and validation.",
    contact_email_label: "Email",
    contact_linkedin_label: "LinkedIn",
    contact_github_label: "GitHub",
    contact_github_value: "ThomasLabetouille",
    contact_cv_label: "Resume",
    contact_cv_value: "Download my resume",
    contact_cv_file: "/CV_Thomas_Labetouille_EN.pdf",
    footer: "C++ / C# Software Developer · Toulouse, France",

    detail_back: "← Back to projects",
    detail_role: "Role",
    detail_engine: "Engine",
    detail_year: "Year",
    detail_highlights: "// What I built",
    detail_tech: "Technologies",
    detail_itch: "↗ Download on itch.io",
    detail_all: "← All projects",
    detail_prev: "← Previous project",
    detail_next: "Next project →",

    gallery_claude_panel: "Claude AI panel inside the UE5 editor",
    gallery_claude_level: "Procedural level design generated by the agent",
    gallery_claude_python: "Real-time Python execution from the chat",
    gallery_claude_blueprint: "Blueprint editing via BatchWireGraph",
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState("fr");
  const t = (key) => translations[lang][key] ?? key;
  const tSkills = () => translations[lang].skills;
  const tProject = (id) => projectsData[lang][id] ?? projectsData.fr[id];
  const tExperience = () => translations[lang].experience;
  return (
    <LangContext.Provider value={{ lang, setLang, t, tSkills, tProject, tExperience }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
